#!/usr/bin/env bash

# Show (the last) job stderr and stdout. Logs must be in slurm-log/


SLURM_LOG_DIR=/net/archive/groups/plggneuromol/slurm-log/

JOB_ID=$(ls -lt $SLURM_LOG_DIR | grep "$(id --user --name).*$1" | \
    head -1 | cut -d. -f1 | rev | cut -d\  -f1 | rev)

tail -n +1 $SLURM_LOG_DIR/$JOB_ID.*
